version: "3.9"

services:
  soap-server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: python-soap-server
    working_dir: /app
    networks:
      - app-network
    volumes:
      - ./backend:/app
      - ./data:/app/data
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/?wsdl"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  graphql-server:
    build:
      context: ./backend
      dockerfile: src/graphql/Dockerfile
    container_name: python-graphql-server
    working_dir: /app
    networks:
      - app-network
    volumes:
      - ./backend:/app
      - ./data:/app/data
    ports:
      - "8001:8000"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/graphql"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
