version: "3.9"

services:
  soap-server:
    image: python:3.10-slim-buster
    container_name: python-spyne-sqlite-server
    working_dir: /app

    volumes:
      - ./src:/app
      - ./data:/app/data

    ports:
      - "8000:8000"

    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/?wsdl"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

    # Corrigido o entrypoint para garantir que é uma única string válida para bash
    entrypoint: >
      bash -c " \
      apt-get update && apt-get install -y sqlite3 && \
      pip install --upgrade pip && \
      pip install -r /app/requirements.txt && \
      gunicorn --bind 0.0.0.0:8000 --workers 4 app:wsgi_app --log-level info \
      "
    restart: unless-stopped
